### PR TITLE
feat(component): mega menu alt

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://todaydesign.atlassian.net/browse/UOM17-123

[Mega menu Alt](https://deploy-preview-1630--pattern-lib-unimelb.netlify.app//?selectedKind=Mega%20menu&selectedStory=Mega%20Menu%20Alt%20%28Today%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

- [x] Add mega menu items coming via props as well, so the CMS can handle the data.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [x] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [x] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit d79cb04ff01a644161776acd4169643024346018

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60a712227863380007328ee8

**Comment by lmounsey** [comment]
@jaredhenderson - the search might not be optimal on mobile - we can add a `InlineSearch` form to the mobile menu and remove the button from header on mobile if that's a better outcome

**Comment by lmounsey** [comment]
We've also got some updates requested that I'll update now:

> 1. Very top nav
> Add Alumni  to the right of ‘Library’ in the very top nav
> 2. Main nav
> Remove About us from the main nav
> Add Safety and respect to the main nav (after ‘Research and innovation’)
> Link safety and respect to this page (https://students.unimelb.edu.au/campus-life/policy-and-conduct/respect-at-the-university)

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
> the search might not be optimal on mobile - we can add a `InlineSearch` form to the mobile menu and remove the button from header on mobile if that's a better outcome
- [x] I think the above is probably a good idea, that overlay is not really optimised for mobile unfortunately

- [x] Is the 'Home' link redundant? We're already on that page, the logo also directs you there anyway, etc. Seems a bit confusing (we're not planning to use this anywhere other than the homepage at this stage)

- @gepifanio would it be better to use the existing 'skip to content' component? Will it be a double-up if we get that other component added to the page separately?

**Comment by gepifanio** [comment]
- [ ]  Add mega menu items coming via props as well, so the CMS can handle the data.

**Comment by lmounsey** [comment]
Hi @jaredhenderson - good catch on the 'Home' link - I've confirmed with the team that this was hangover from global nav exploration. I have removed it

**Comment by jaredhenderson** [comment]
- [ ] Hey @lmounsey , are you able to check how the mobile menu enters on shorter mobile viewports? I'm checking with an iPhone SE resolution (320 x 568px) and the menu is taller than the viewport, which is fine, but it enters slightly clipped off at the top... like it's outside of the page slightly

Looks pretty good otherwise.

Screen Shot 2021-05-24 at 2 32 08 pm

**Comment by lmounsey** [comment]
@jaredhenderson - looks like it was focussing the last link on open hence the scroll - have submitted a fix for this

**Review by lmounsey — APPROVED** [review]

**Review by jaredhenderson — APPROVED** [review]
👍 looks good

**Review by anormand — APPROVED** [review]
Passes accessibility check. Keyboard interaction good, menu spacing on mobile passes 44 px test, semantic structure good, Voiceover+Chrome good

**Pull request merged**
