### PR TITLE
feat(component): button card

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://jira.unimelb.edu.au/browse/VOD-111

preview: https://deploy-preview-1466--pattern-lib-unimelb.netlify.app/?selectedKind=Buttons%2FTypes&selectedStory=Button%20Card&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit baa4932708a14632295d2eccfa2716cfa7629c2c

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5f22391db108e000081824d8

**Comment by jaredh-um** [comment]
Hey Gui,

These look to be matching the designs really well. A few things:

**Comment by jaredh-um** [comment]
Thanks for updating. Are you able to add some properties like this for the hover and active state animations:

```
.btn-card__icon {
    transition: scale .1s ease-out;
    scale: 1.0;
}

.btn-card:hover .btn-card__icon {
    scale: 1.1;
}

.btn-card:active .btn-card__icon {
    scale: 0.9;
}
```

I'm guessing from the class names that this might impact some other components though?

**Comment by jaredh-um** [comment]
Also I just checked with Andy and the arrow icon can be hidden from screenreaders because they will already know it's a link. He suggests using `aria-role="hidden"`

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute

**Comment by jaredh-um** [comment]
Sorry Gui, just went to preview and there's one more change to get the animation working... I previously had the `scale` property as the one to animate, but since you're using `transform` instead (which is better for browser compatibility) you need to change the animated property to `transform` instead of `scale`.

- [ ] Adjust  `transition: scale .1s ease-out;` to be ` transition: transform .1s ease-out;`

**Pull request merged**
