### PR TITLE
fix(component): header l3

### PR DESCRIPTION
**Pull request by gepifanio**
Ticket: #1135

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit cad3ceb6f823e5e57361018c83dca14527ff5e30

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5d12d9c7cec85b0008b49ce1

**Comment by woowoowoo** [comment]
Looks good to me, Gui.

**Comment by TimMansell** [comment]
Also, as per discussion with @jaredh-um can you delete the `logo-responsive.svg` and use the new Logo component.  Will need to merge PR #1140 first.

**Comment by TimMansell** [comment]
Also, update CSS so the zig-zag background doesn't flow behind the logo.

Screen Shot 2019-06-27 at 1 31 40 pm

**Pull request merged**
