### PR TITLE
Component 95 - Focus section

### PR DESCRIPTION
**Pull request by codeuri**
Added button to Focus section stories
Closes https://github.com/unimelb/ffam-prototype/issues/95

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 14f0fb59d366e2105783351472cd35dee9b36d41

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5c813852a7045100084649d3

**Comment by meligatt** [comment]
@codeuri this one is on hold at the moment. (comment on zenhub card) cheers.

**Comment by gepifanio** [comment]
This PR is related to which ticket?

I think the button should not be added to all stories and should be:

- created a new story showing how is the Focus Section with button
- how can be used this Focus Section in component mode ( `<SectionFocus header="" button="" ....>` )
- if any of the options are not passed, do not render the respective option.

**Comment by codeuri** [comment]
Hi @gepifanio 
Thank for advice, but I a little bit confused.
As I see in the component code it not provide the ability to have dynamic header/button/text. It has only one slot where we can add content. Also, I don't see such requirements in the task for CardFocusBox component. Please advise?

PR title changed.
Added separate story with the button.

Thanks

**Comment by gepifanio** [comment]
> Hi @gepifanio
> Thank for advice, but I a little bit confused.
> As I see in the component code it not provide the ability to have dynamic header/button/text. It has only one slot where we can add content. Also, I don't see such requirements in the task for CardFocusBox component. Please advise?
> 
> PR title changed.
> Added separate story with the button.
> 
> Thanks

Hello @codeuri 
Not a problem, feel free to ask whenever you want ;)
That's true this component is not prepared for that type of use (`<component>`) so do not worry about it. 
Thank you for implementing the changes. 

Cheers!

**Pull request merged**
