### PR TITLE
Comp - 221: Mega menu title update

### PR DESCRIPTION
**Pull request by codeuri**
- added aperture option
- added aperture color prop
- unit tests
- styling

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 55e1ef982994bb6ab643a53a2483991562206399

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5c8bcc613fcce80008ea7063

**Comment by TimMansell** [comment]
I've started work on refactoring code so aperture works on mobile

**Comment by meligatt** [comment]
@TimMansell hi tim..I'm not clear what are the changes you want to do..can you add a description? thankssss

**Comment by meligatt** [comment]
@TimMansell added some updates to what you updated, I will merge. Support for "color" aperture was done by @codeuri but for now It's not working with your changes. default is back which is good enough fo now to test for FFAM. cheers. 

@codeuri I will create another card to update color for aperture bg. Thanks a lot.

**Pull request merged**
