### PR TITLE
chore: chevron link styling and add chevron article list

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

- Changed margin between button link text and chevron 
- Added button link text to article list

*Matrix CMS* attention

- Removed custom class `article-card__link`
- Markup changed component `CardArticleList`

[Preview Button Text Link](https://deploy-preview-1820--pattern-lib-unimelb.netlify.app/?selectedKind=Buttons%2FTypes&selectedStory=Text%20link&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[Preview Card Article List](https://deploy-preview-1820--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FCards&selectedStory=Article%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

Fixes https://jira.unimelb.edu.au/browse/TS-1679

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export
- [x] Added proper labels to the PR and if there are any markup changes add `markup changes` label too.

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested
## Check List Before Merging

- [ ] Relevant Draft release notes have been updated describing these changes ([use this template](https://github.com/unimelb/pattern-lib/blob/dev/.github/RELEASE_NOTES_TEMPLATE.md) to document your changes) `(if applicable)` especially markup changes.

### CODE REVIEW

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
Hey @gepifanio, this is mostly looking right but the chevron size isn't quite right for both cases.
- Text-only button chevron should equal 8 x 8px
- Chevron after article heading should be 10 x 10px

At the moment they are both using `.6rem` which is equating to 9.6px - I want to avoid using sub-pixel values whenever possible.

The difference between the two is small but relates to the text size the chevron is aligned to as [shown in Figma](https://www.figma.com/file/E1vWS4bxzy21BI3De39DDn/UI-Kit?node-id=4209%3A21479).

**Comment by jaredhenderson** [comment]
Hey @gepifanio, the chevron sizes are better but I noticed the margin between the text and chevron looks bigger than expected for both the text-only button and the article heading links.

If you check them in the browser, they all have an extra `space` character at the end of the span which is making the gap appear too big.

Screen Shot 2021-12-21 at 10 48 31 am

Are you able to check if these can be removed?

**Comment by gepifanio** [comment]
> 

Hey @jaredhenderson those extra spaces seem to be odd, I had a look and did some research.

I cant find how to get it fixed, so annoying 😞

**Comment by jaredhenderson** [comment]
Hi @gepifanio, I'm going to log the whitespace bug as a separate issue. It appears to affect almost every Vue string I can see. There is actually a lot more whitespace in the DOM string than is being displayed, but that's only because the browser is stripping most of it out by default.

I've logged the details as [TS-1688](https://jira.unimelb.edu.au/browse/TS-1688) so that issue can be looked at separately as it appears to be a very undesirable bug.

**Review by jaredhenderson — APPROVED** [review]
Looks good. Hopefully the extra whitespace issue can be resolved separately

**Pull request merged**
