### PR TITLE
feat(component): header text with cta 2 column

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes
https://jira.unimelb.edu.au/browse/VOD-109
https://jira.unimelb.edu.au/browse/VOD-128

preview:

[header text with cta](https://deploy-preview-1469--pattern-lib-unimelb.netlify.app/?selectedKind=Section%2FTwo%20Column&selectedStory=Header%20text%20with%20cta%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 222303ab5e6dbf9fd3a305f0143612128f30b182

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5f27ae4ef8f77800072af6e0

**Comment by jaredh-um** [comment]
Hey Gui, there needs to be some spacing added to the middle of this component to separate the heading and paragraph text further.

### Natasha design
Screen Shot 2020-08-04 at 10 17 41 am

### Pattern Library
Screen Shot 2020-08-04 at 10 17 23 am

You can check my [Figma file](https://www.figma.com/file/A82AMbwq1tv2tsRmr4jCBB/VOD-2020-Components?node-id=26%3A0) for a version of this component with spacers to show the separation.

**Comment by jaredh-um** [comment]
- [ ] Mobile design is switching over at 480w - could we make this a bit earlier so the columns don't get too small? maybe at `--bp-max-x-mobile` (or approx ~580-600w)
- [ ] Font sizes need to be adjusted for tablet and mobile breakpoints to match [design](https://www.figma.com/file/UbIJDUYgxpPMkOZQ9mhXf2/UoM-Open-Day-Squiz-Pages?node-id=418%3A489)
- [ ] Margin need to be increased on mobile between heading and paragraph text

**Comment by jaredh-um** [comment]
Looks good! Can we just change the button on mobile...

- [ ] add class `btn--xsml` for mobile

**Pull request merged**
