### PR TITLE
Add new inline search component and alternative search icon

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

Previews:

[With submit button](https://deploy-preview-1603--pattern-lib-unimelb.netlify.app/?selectedKind=Forms&selectedStory=Inline%20search%20form%20with%20submit%20button%20%28Today%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

[Without submit button](https://deploy-preview-1603--pattern-lib-unimelb.netlify.app/?selectedKind=Forms&selectedStory=Inline%20search%20form%20without%20button%20%28Today%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

[On dark backgrounds](https://deploy-preview-1603--pattern-lib-unimelb.netlify.app/?selectedKind=Forms&selectedStory=Inline%20search%20form%20dark%20bg%20%28Today%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

New component for inline search style used through the Study website and potentially the homepage (in mobile menu). Contains modifier for dark background to invert the button colour and some other slight variations. Can work with/without a submit button.

Have also added another icon - `search-alt` - I tried using the existing one but it looked quite odd with the new style. Is this OK to add an additional icon? Or perhaps replace the current one?

I've also introduced a new grey `--col-grey-mid-0` - this is used as the hover background on the submit button on the dark version - I believe this is a variation of `--col-grey-light` with -10% lightness.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 00f7c626901eb6bd912b2dc77891f80538ba984c

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/6090d4a612b16d0008d3894e

**Review by jaredh-um — CHANGES_REQUESTED** [review]
Hey Lucas,

Looks good. Some feedback:

- [x] Do replace old search.svg icon with your new one, we don't need two so similar
- [ ] If the new `--col-mid-grey-0` is a one-off, I would prefer it was hardcoded in this instance rather than available as a global var

**Review by gepifanio — APPROVED** [review]
Looks good for me.

**Review by jaredh-um — APPROVED** [review]
Looks good 👍

**Review by gepifanio — CHANGES_REQUESTED** [review]
I forgot to ask and mention before, but could you please also add unit testing for the component, you could follow the same example like this one I am doing for the PathfinderToday:

```

import {
  shallow,
} from 'vue-test-utils';
import { axe, toHaveNoViolations } from 'jest-axe';
import PathfinderToday from '../PathfinderToday.vue';

expect.extend(toHaveNoViolations);

const pathfinderLinks = [
  {
    title: 'Undergraduate courses',
    description: 'Flexible first degrees that you can tailor to your career goals, or explore new possibilities.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate courses',
    description: 'Study in small classes led by experts alongside others who share your interests and goals.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate research',
    description: 'Access dedicated research centres, advanced  facilities, generous scholarships and more.',
    href: '/landing-page/',
  },
  {
    title: 'Short&nbsp;courses&nbsp;and microcredentials',
    description: 'Upskill, expand your knowledge and take the next step in your career with focused courses.',
    href: '/landing-page/',
  },
];

describe('PathfinderToday', () => {
  it('should match snapshot', () => {
    const result = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).element;
    expect(result).toMatchSnapshot();
  });

  it('Component throws no accessibility violations', (done) => {
    const html = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).html();
    // pass anything that outputs html to axe
    return axe(html).then((response) => {
      expect(response).toHaveNoViolations();
      done();
    });
  });
});
```

**Comment by anormand** [comment]
1. Poor test environment

Problem:

Storybook is a poor test environment because the components contain a lot of hidden code that creates accessibility errors, e.g. the form 'Register you details'.

This makes testing unreliable and slow.

Remedy:

See [TS-1042	[Accessibility] Create pattern library test site](https://jira.unimelb.edu.au/browse/TS-1042)

2. Multiple labels

Problem:

All of the example input fields have the same id. As a result the label 'Search the University' gets read out multiple times.

Remedy:

Give each search field a different id.

3. Search as you type label

Problem:

The auto-updating input field has a label of 'Search the University', which doesn't indicate that content is changing

Remedy:

Change the label for search as you type.

Change:
<label for="site-search" class="screenreaders-only">
  Search the University
</label>

To:
<label for="site-search" class="screenreaders-only">
  Search the University. Typing automatically updates the results below
</label>  

4. Storybook documentation
We need to included the expected screen reader announcement in the Storybook documentation (see below).

</h4>Screen reader announcement (Voiceover)</h4>

With submit button
- Search the University, search text field, Search the University
- Submit, button

Without submit button
- Search the University. Typing automatically updates the results below, search text field, search

On dark backgrounds
- Search the University, search text field
- Submit, button

**Comment by lmounsey** [comment]
I've committed a fix for points 2,3 and 4.

**Comment by anormand** [comment]
Problems:
1. SortSite displays an error for this page, because of the repeated use of the Submit label. Can we split these buttons into seperate component previews? 
2. The autoupdating search would only be used on things like course search, not site search. Can we change the placeholder text to 'Search courses'?
3. As the Siteimprove checker reports, the focus indicator for the first Submit button isn't visible because it is blue, like the button. Add a white border on the interior.

**Pull request merged**
