### PR TITLE
feat(component): pathfinder today

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://todaydesign.atlassian.net/browse/UOM18B-112

## Component preview
[Pathfinder - Default](https://deploy-preview-1612--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FPathfinder&selectedStory=Default)
[Pathfinder - Inline Dark](https://deploy-preview-1612--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FPathfinder&selectedStory=Inline%20Dark)
[Pathfinder - Slot](https://deploy-preview-1612--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FPathfinder&selectedStory=Slot)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit d72f180e033b3c856aeb9e85922346e74bb9c1b8

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60988b309d47550007f500bf

**Comment by gepifanio** [comment]
@lmounsey 

Added new Pathfinder into the Pattern-lib.

I changed 2 things into the code:

- Removed slot prop
- Changed prop `items.title` instead of being `v-html` to be a simple string.

I want to validate, those to points, why we would need a slot in there, and why the title was a HTML.

Thanks =)

**Comment by lmounsey** [comment]
Hey @gepifanio - one more to add

Could you please add an `aria-hidden="true"` attribute to the `SvgIcon` component? It came up as an issue in the home page audit

New code should be

```
<SvgIcon
     name="arrow-right"
     aria-hidden="true" />
```

**Review by jaredh-um — CHANGES_REQUESTED** [review]
A few changes/suggestions:

- [x] `Story2.vue` - suggest wrapping the `PathfinderToday` component in a simple `div`, as our `SectionWrap` component adds a lot of extra padding/whitespace to the section

- [ ] Hover states for arrow icons seem to be different from the prototype (basically fades the circle out entirely)

- [ ] Is it possible to amend the structure of the pathfinder tiles so the `a` link is only wrapping the heading and arrow icon, not the description? Two reasons - don't want the whole block to be clickable as this is a previous design pattern we have progressively been removing; second is that screen readers will read the entire contents of the card as it's a link, this should be restricted to just the heading to keep things concise
- [ ] Potential workaround for the two-line heading issue - amend padding on text container to match Figma, then set a `min-height` on the text container of 2x line height. This will allow 1 and 2 line headings to have their description text start at the same vertical height across columns; it will break on 3 lines but this is unavoidable without significant refactoring (CSS grid hacks)

**Review by jaredh-um — CHANGES_REQUESTED** [review]
- [ ] Text decoration in pathfinder blocks is not being inherited on anchor link (heading) - should be `text-decoration: none` in default state, can show underline on `hover` (currently this behaviour is reversed) - this only applies to the headings with arrows next to them, not the standard text links in the search version

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
- [x] Add `min-height:calc((1.125rem*1.4)*2)` to `.pathfinder-today__link-title` so heading takes up a minimum of 2 * `line-height` and balances out the description text, as per previous comment

**Before:**
Screen Shot 2021-05-12 at 1 11 13 pm


**After:**
Screen Shot 2021-05-12 at 1 10 54 pm

**Review by jaredhenderson — APPROVED** [review]
Description text looks like it could be a bit narrow between `481 - 599px` viewport width, but as there is no design reference I'm going to leave it. Looks good now otherwise 👍

**Comment by gepifanio** [comment]
- [ ] add aria role of navigation

**Comment by anormand** [comment]
### Pathfinder - Default

Problem
- The pathfinder functions as a set of navigation links, but this isn't indicated to assistive technologies

Solution
- Give the pathfinder a role of navigation

Example
Change
`<div class="pathfinder-today__link">`

To
`<div role="navigation" class="pathfinder-today__link">`



### Pathfinder - Slot

**1. Search border**

Problem:
- The border around the search input field has a contrast ratio against the background of 1.2:1

Remedy:
- Increase the contrast ratio to 3:1

Example:
Change
`border: 1px solid hsl(180,2.5641025641%,87.3529411765%);`
To
`border: 1px solid hsl(180,2%,53%);`

**2. Duplicate labels**

Problem:
- The search input field has both a <label> and an aria-label. Both are different

Remedy:
- There only needs to be one label. aria-label will be announced in preference to <label>

Example:

Change
```
<label for="search-input" class="heading-card" style="">Search careers, interests, courses or specialisations</label>
...
<input id="search-input" aria-label="Course title or keyword" type="search" placeholder="Type to search courses" class="form--inline__search" style="">
```

To
```
<label for="search-input" class="heading-card" style="">Search careers, interests, courses or specialisations</label>
...
<input id="search-input" aria-label="Search careers, interests, courses or specialisations" type="search" placeholder="Type to search courses" class="form--inline__search" style="">
```

**3. Popular searches**

Problem
- The paragraph 'Popular searches' is followed by a list but they aren't semantically connected, i.e. assistive technologies aren't told that the <p> is connected to the <ul>

Remedy
- Give popular searches a role of navigation and add an aria-labelledby attribute

Example
Change
```
<div class="col-xxs-12 col-sm-6"><p class="paragraph-sm shim-mb0" style="">
<p class="paragraph-sm shim-mb0" style="">
  Popular searches:
</p>
<ul class="list-inline paragraph-sm"><li><a href="/find/?s=Science" style="">Science</a></li> <li><a href="/find/?s=Business" style="">Business</a></li> <li><a href="/find/?s=Bachelor%20of%20Design" style="">Bachelor of Design</a></li> <li><a href="/find/?s=Criminology" style="">Criminology</a></li></ul>
</div>
```

To
```
<div role="navigation" aria-label="Popular searches" class="col-xxs-12 col-sm-6"><p class="paragraph-sm shim-mb0" style="">
<p class="paragraph-sm shim-mb0" style="">
  Popular searches:
</p>
<ul class="list-inline paragraph-sm"><li><a href="/find/?s=Science" style="">Science</a></li> <li><a href="/find/?s=Business" style="">Business</a></li> <li><a href="/find/?s=Bachelor%20of%20Design" style="">Bachelor of Design</a></li> <li><a href="/find/?s=Criminology" style="">Criminology</a></li></ul>
</div>
```

**Comment by angieraj** [comment]
@gepifanio can you assign to Andy once this is ready for retest

**Review by lmounsey — COMMENTED** [review]
```
          <div
            role="navigation"
            class="pathfinder-today__link">
```
I'm wondering if this needs to be on the surrounding element of the list, not each link item?

@gepifanio @anormand

**Comment by anormand** [comment]
Yes @lmouinsey, the navigation role needs to go on the <div> surrounding the <ul>, not on the <div> within the <li>. My previous example was confusing, sorry.
Please change:
<div class="pathfinder-today">
To:
<div role="navigation" class="pathfinder-today">

**Pull request merged**
