### PR TITLE
feat: add in page nav from today into pattern-lib

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

- Port over in-page navigation from study to pattern-lib

[preview](https://deploy-preview-1736--pattern-lib-unimelb.netlify.app/?selectedKind=Navigation&selectedStory=In%20page%20Navigation%20Today&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

Fixes https://jira.unimelb.edu.au/browse/TS-1295

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
preview mobile version icons doesn't have the gradient

preview:
image
image

localhost:
image

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
Looks pretty good. Can you make one tweak to the gradient background on the mobile nav buttons...
Currently the gradient has a hard edge because the starting position is `-23.89%`.

Screen Shot 2021-08-18 at 11 39 05 am


Can you adjust the backgrounds on both of these buttons to be more like the following:
`linear-gradient(90deg, rgba(237,242,245,0) 0%, rgba(237,242,245,.5) 40%, #edf2f5 95%)`

which looks like this:

Screen Shot 2021-08-18 at 11 38 45 am

**Comment by jaredhenderson** [comment]
Re: use of `overlay` for `overflow` - non-standard property that isn't well supported:
https://caniuse.com/?search=overlay

**Review by jaredhenderson — APPROVED** [review]
Looks good 👍

**Pull request merged**
