### PR TITLE
chore(component): channel bar titles

### PR DESCRIPTION
**Pull request by gepifanio**
TIcket: [#527](https://github.com/unimelb/ffam-prototype/issues/527)

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit b585fd01532d84cdfaf4e51b0024794e045aa5dc

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5d37f9663b2316000807a33c

**Comment by jonathan-doc** [comment]
Just two minor changes:
- [ ] Set link line-height to **1.0625rem** (17px)
- [ ] On Mobile only, set the link margin-bottom to **1rem** (16px)

Thanks!

**Comment by TimMansell** [comment]
An update to @jonathan-doc lin-height.  Use `line-height: 1.06;` to make it 17px.

**Comment by jonathan-doc** [comment]
- [ ] Set **social-media-bar__inner** padding-bottom to **0.5rem** / 8px
 (since the last change to the margin is also adding to the social icons')

Should be all good otherwise

**Pull request merged**
