### PR TITLE
chore(component): page footer alt css fixes

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://github.com/unimelb/pattern-lib/issues/1690

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
@jaredhenderson I am just unsure what to do with the Logo and social links within the screen resizing.

**Comment by jaredhenderson** [comment]
Changes look good so far. There is no reference from Today in their Figma files for the mobile/tablet versions of the footer, so that's probably why the logo etc. doesn't have a "home" at those sizes. I'll transfer their designs to our Figma system and do the responsive versions and let you know when that is done.

**Comment by jaredhenderson** [comment]
Ok, responsive designs available in our Figma:
https://www.figma.com/file/UF2630XlnsbudpZgvyZec0/Gen-2-and-3-Master-Components?node-id=2251%3A25035

Changes include:
- alignment of logo and social icons to centre below desktop
- font size consistency between breakpoints
- spacing
- telephone numbers are together
- line height and margins between the two text columns are compatible on desktop/tablet

**Comment by gepifanio** [comment]
> Ok, responsive designs available in our Figma:
> https://www.figma.com/file/UF2630XlnsbudpZgvyZec0/Gen-2-and-3-Master-Components?node-id=2251%3A25035
> 
> Changes include:
> 
> * alignment of logo and social icons to centre below desktop
> * font size consistency between breakpoints
> * spacing
> * telephone numbers are together
> * line height and margins between the two text columns are compatible on desktop/tablet

I have applied the fixes, hopefully I could address it all :)

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
This is looking pretty good. Some minor things:
- The text is lining up better between the 2 text columns, you've got the right values in there (basically the `line-height` of the text is 24px/1.5rem, so as long as the `margin-bottom` has the same value then all the text will line up nicely)
- [ ] However, when I'm testing in Firefox, the primary links are calculating as `25.8667px` instead of `24px` for some reason
Screen Shot 2021-07-19 at 10 50 01 am
- [ ] Bottom margin needs to be reduced on secondary links at tablet and below breakpoints

**Review by jaredhenderson — APPROVED** [review]
Looks good!

**Pull request merged**
