### PR TITLE
fix(component): mega menu keyboard navigation

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://todaydesign.atlassian.net/browse/UOM18B-247

[Iframe preview](https://deploy-preview-1685--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Mega%20menu&selectedStory=Mega%20Menu%20with%20Top%20nav)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by angieraj** [comment]
Thanks @gepifanio looks good! Some of the issues we should try and tackle: 

1. The dropdown doesn't always work 
2. No delay when opening the sub menu items - so should work similar to the menu on https://students.unimelb.edu.au/ when tabbing through

**Comment by angieraj** [comment]
Thanks @gepifanio Those 2 points seem to be addressed now. I've tested it across browsers now too and Firefox seems to be having some issues, the menu doesnt highlight at all - see attached recording. Cant you please check what might be happening here?

https://user-images.githubusercontent.com/47799409/124415631-9933ac00-dd98-11eb-86e6-47e1f1b8aa2e.mov



Also not sure if this is something but the outline around the sub menu items looks strange when tabbing through, can we make this just a rectangle border around the word like you have done for the the first level sub menu items (see attached) 

Screen Shot 2021-07-05 at 1 52 00 pm
Screen Shot 2021-07-05 at 1 50 42 pm

**Comment by gepifanio** [comment]
@angieraj I think your Firefox issue could be related to it not be able to use keyboard navigation have a look at this article it might help enabling it to use the keyboard: https://www.456bereastreet.com/archive/200906/enabling_keyboard_navigation_in_mac_os_x_web_browsers/

if you need help let me know.

**Comment by angieraj** [comment]
Thanks @gepifanio that helped and working fine in Firefox now. Just need to address that border issue I think, i'm seeing that disconnected border on Chrome and Safari.

**Comment by jaredhenderson** [comment]
The keyboard tabbing appears to work fine now @gepifanio but there are some weird issues with the focus ring on different parts of the menu:

- Main menu items
Screen Shot 2021-07-08 at 10 15 15 am

- Child links
Screen Shot 2021-07-08 at 10 15 32 am
Screen Shot 2021-07-08 at 10 15 41 am

- Search button
Screen Shot 2021-07-08 at 10 15 58 am

These should be appearing similar to this link, with the focus border visible on all sides, standard thickness:
Screen Shot 2021-07-08 at 10 18 00 am

This is happening in Firefox, Chrome, Safari (Firefox has different focus border styling though).

- [ ] Ensure focusable items have full focus ring visible on all sides, in a consistent pattern

**Comment by angieraj** [comment]
Just on this @gepifanio any chance we can resolve this by 2pm today as that's when Andy is doing his accessibility check and I'd like him to do his review with this merged.

**Comment by angieraj** [comment]
Thanks @gepifanio Looks really good now!

**Comment by jaredhenderson** [comment]
This is looking better in most places (especially with Firefox as the focus ring is smaller), still a couple of slight issues with Safari/Chrome:
Screen Shot 2021-07-08 at 2 52 00 pm

- Focus ring is wrapping across two columns in this example (the bottom border is wrapping from column 1 to column 2)
- The chevron is being shrunk by the large amount of text in the other part

Search looks like:
Screen Shot 2021-07-08 at 2 53 05 pm

Should be more like:
Screen Shot 2021-07-08 at 2 56 22 pm

Top and bottom of main menu links are still a bit cut off:
Screen Shot 2021-07-08 at 2 57 14 pm

**Comment by jaredhenderson** [comment]
Focus fixes look good in Safari now too. Only tiny issue remaining is the `chevron` resizing in the previous example with the long heading

**Comment by gepifanio** [comment]
> Focus fixes look good in Safari now too. Only tiny issue remaining is the `chevron` resizing in the previous example with the long heading

True, I forgot about this one, gonna get it fixed.

**Review by jaredhenderson — APPROVED** [review]
Looks good 👍

**Pull request merged**
