### PR TITLE
fix(typhography): headings letter-spacing

### PR DESCRIPTION
**Pull request by gepifanio**
Ticket: https://github.com/unimelb/pattern-lib/issues/1254

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 289afb3a7b3dc2952e3a4426897a3738e2a445fb

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5d67637718cde30007c25357

**Comment by TimMansell** [comment]
@jaredh-um I created a story in `content block > headings` showing all headings contained inside `.content-block`

**Comment by jaredh-um** [comment]
New story works well. Looks like the fixes have mitigated the leakage; if possible can we implement Andrew's recommendations for the H1 and H2s:
- [ ] `letter-spacing: -0.05rem`
- [ ] `word-spacing: 0.05rem`

**Comment by jaredh-um** [comment]
@gepifanio @TimMansell 
The following examples are still 'leaking' through some elements of the spacing adjustments because they're affecting the class being used:

Screen Shot 2019-09-02 at 1 26 09 pm
Screen Shot 2019-09-02 at 1 25 07 pm

Can check this on the [Storybook deploy.](https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Content%20Block&selectedStory=Headings&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

**Pull request merged**
