### PR TITLE
fix: The iframe element must not appear as a descendant of an element role button

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

- Added a new field in the data array to accept video `thumbnail`.

image

- Tested with SortSite ✅ 

@dkevey and I had a chat, in order to make this component accessible we needed to display the video thumbnail instead of the video iframe, however, we had two options to make this work:

1 - Frontend to have a javascript function to identify the video host + video id + video thumb and display it.
2 - CMS editors to provide the thumbnail URL

After the research, this component usage is really low in the CMS, and the video option usage is even lower, is not worth spending the time and effort to implement something that won't be highly used. So we decided to add a new data attribute into the Frontend to just render the thumbnail. 

Fixes https://jira.unimelb.edu.au/browse/TS-1302

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export
- [x] Added proper labels to the PR and if there are any markup changes add `markup changes` label too.

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested
## Check List Before Merging

- [ ] Relevant Draft release notes have been updated describing these changes ([use this template](https://github.com/unimelb/pattern-lib/blob/dev/.github/RELEASE_NOTES_TEMPLATE.md) to document your changes) `(if applicable)` especially markup changes.

### CODE REVIEW

**Comment by jaredhenderson** [comment]
- Please explain what you've changed
- Please indicate the impact this will have
- Please indicate if you have tested this manually
- Please indicate if it passes SortSite

Adding a Jira link and copying a SortSite line is not sufficient information for me to be able to review.

**Comment by gepifanio** [comment]
> * Please explain what you've changed
> * Please indicate the impact this will have
> * Please indicate if you have tested this manually
> * Please indicate if it passes SortSite
> 
> Adding a Jira link and copying a SortSite line is not sufficient information for me to be able to review.

Updated description

**Comment by jaredhenderson** [comment]
> Updated description

You still don't mention if you've tested it. What impact does removing the `button` role have on keyboard navigation, etc?

**Comment by gepifanio** [comment]
> > Updated description
> 
> You still don't mention if you've tested it. What impact does removing the `button` role have on keyboard navigation, etc?

Tested manually, it loses the ability to navigate through keyboard using each thumb item, the user has the use the arrows to go into next or previous.

**Comment by jaredhenderson** [comment]
- We should never have been loading video iframes as thumbnails in the first place. Can you amend the component so it gets the video poster image instead?

- This change negatively impacts accessibility in another way, by making the navigation less usable. SortSite might not report this, but it is definitely the case. If this is how you are planning to "fix" this issue I think you should get Andy to review the changes to the component.

**Pull request merged**
