### PR TITLE
chore(component) global button style changes

### PR DESCRIPTION
**Pull request by TimMansell**

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 29d1ccc24488c9e5fec5f41b34a157807ea02baf

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5d2fed9e6ded3600086fbad3

**Comment by jonathan-doc** [comment]
Looks good - only spotted these:

- [ ] Remove border on Secondary Button (like CTA button)
- [ ] Set the button padding to **10px 16px 10px 20px**

**Comment by TimMansell** [comment]
@jonathan-doc, done.

You and @jaredh-um may want to review the button sizes `extra small` & `small` as they similar sizes or even larger than the `default` button now.

**Comment by TimMansell** [comment]
Also dark campaign banner button text colour is different. Should we remove the component colour override?

```
.page-campaign__btn--dark {
    color: #7cbdcd;
}
```

https://deploy-preview-1206--pattern-lib-unimelb.netlify.com/?selectedKind=Campaign&selectedStory=Dark%20Background&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by jonathan-doc** [comment]
> Also dark campaign banner button text colour is different. Should we remove the component colour override?
> 

Yep, default and hover text colour can be set to #FFFFFF – it's basically 'Inverted button'

Other changes:
- [ ] The 'No Icon' button padding can be set to **10px 16px** (since there's no icon making the spacing uneven)
- [ ] For the Next / Previous buttons, the left / right properties for the chevron should be set to 16px, and the padding-left / padding-right for the button should be set to 40px

I'll discuss the other sizes with Jared tomorrow

**Comment by jaredh-um** [comment]
Hi @TimMansell, can we adjust the padding on the other buttons as follows:

`btn--sml` - `padding: .5rem 1rem`
`btn--xsml` - `padding .375rem 1rem`

Screen Shot 2019-07-31 at 8 53 20 am

**Comment by TimMansell** [comment]
Done button `btn--sml` & `btn--xsml` changes.

**Comment by TimMansell** [comment]
@gepifanio you can pick up this ticket if you need something to do.  Just need updates to Next / Previous buttons.

**Comment by gepifanio** [comment]
@TimMansell Should we be good to merge it?

**Comment by jonathan-doc** [comment]
Hey @TimMansell @gepifanio, we're just going to work on the styles for the booking button, would be good to get those in before the merge :)

**Comment by jonathan-doc** [comment]
Also just noticed that there's something wrong with the states for the [Secondary Button](https://deploy-preview-1206--pattern-lib-unimelb.netlify.com/?selectedKind=Buttons&selectedStory=Secondary%20Button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

Assuming this is the equivalent of the [White (Solid)](https://zeroheight.com/17lwnkf17/p/378949/t/27a58e) button, it shouldn't have a border either.

**Comment by TimMansell** [comment]
> Hey @TimMansell @gepifanio, we're just going to work on the styles for the booking button, would be good to get those in before the merge :)

Is this the `event` button or a new button?

**Comment by jonathan-doc** [comment]
> > Hey @TimMansell @gepifanio, we're just going to work on the styles for the booking button, would be good to get those in before the merge :)
> 
> Is this the `event` button or a new button?

Sorry yep the 'event' button

**Comment by jonathan-doc** [comment]
Okay @TimMansell @gepifanio the spec is up on [Zeroheight](https://zeroheight.com/17lwnkf17/p/378949/t/99c059).

**Comment by TimMansell** [comment]
> Also just noticed that there's something wrong with the states for the [Secondary Button](https://deploy-preview-1206--pattern-lib-unimelb.netlify.com/?selectedKind=Buttons&selectedStory=Secondary%20Button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> 
> Assuming this is the equivalent of the [White (Solid)](https://zeroheight.com/17lwnkf17/p/378949/t/27a58e) button, it shouldn't have a border either.
> 
> EDIT: Don't worry, was just something wrong with mine, just need to remove the border.
> 
> * [ ]  Remove borders from Secondary Button variant

The border is there so they align in height & width compared to the other buttons.  The `border-colors` are the same as the `background-color` (except the active state which I've fixed.)

**Comment by TimMansell** [comment]
I've updated the event button styles.

**Comment by TimMansell** [comment]
@jonathan-doc, can we merge this?

**Comment by jonathan-doc** [comment]
@TimMansell Yep, looks good to go

**Pull request merged**
