### PR TITLE
Feat/testimonials alt new variation

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

### new `CardPortrait` component:

- The card portrait component handles [portrait video](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FPortrait&selectedStory=Portrait%20Video%20with%20Preview&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel), [portrait mixed video and images](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FPortrait&selectedStory=Portrait%20Image%20and%20Video%20with%20Preview&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
- The card Portrait component has two new props ( `link`, `imageOnly` )
- Card portrait prop `name` changed to `description`
- Card portrait has a new prop called `altText` to handle the `alt text` into the images

### `TestimonialsAlt` component:

- Handles the [text](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FTestimonials&selectedStory=Text&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) and [text long](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FTestimonials&selectedStory=Text%20%28Long%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) testimonials

Fixes https://jira.unimelb.edu.au/browse/TS-1695

[Today miro board](https://miro.com/app/board/o9J_ln1yZW0=/)

[Preview portrait video](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FPortrait&selectedStory=Portrait%20Video%20with%20Preview&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

[Preview portrait mixed video and images](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FPortrait&selectedStory=Portrait%20Image%20and%20Video%20with%20Preview&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

## Breaking Change

- TestimonialsAlt component when using `video` and `video and image` portrait have been renamed to `CardPortrait`

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export
- [x] Added proper labels to the PR and if there are any markup changes add `markup changes` label too.

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested
## Check List Before Merging

- [x] Relevant Draft release notes have been updated describing these changes ([use this template](https://github.com/unimelb/pattern-lib/blob/dev/.github/RELEASE_NOTES_TEMPLATE.md) to document your changes) `(if applicable)` especially markup changes.

### CODE REVIEW

**Comment by jaredhenderson** [comment]
A few things:
- [ ] These aren't "testimonials" anymore, that only really describes the video content from the original component. The actual components (video, image and videos) seem like they would fit better into the 'Cards' category in Storybook.
  - Suggested naming: **Cards > Portrait Video with Preview**, **Cards > Portrait Image and Video with Preview**
- [ ] Headings that are links should have a chevron icon added, like the [featured articles component](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FSection&selectedStory=Featured%20Articles&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)(can use same specs as the heading class is the same `heading-sm`)
- [ ] Are these videos supposed to autoplay when scrolled into the viewport? It's hard to test this in Storybook

**Comment by gepifanio** [comment]
> A few things:
> 
> * [x]  These aren't "testimonials" anymore, that only really describes the video content from the original component. The actual components (video, image and videos) seem like they would fit better into the 'Cards' category in Storybook.
>   
>   * Suggested naming: **Cards > Portrait Video with Preview**, **Cards > Portrait Image and Video with Preview**
> * [x]  Headings that are links should have a chevron icon added, like the [featured articles component](https://deploy-preview-1823--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FSection&selectedStory=Featured%20Articles&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)(can use same specs as the heading class is the same `heading-sm`)
> * [x]  Are these videos supposed to autoplay when scrolled into the viewport? It's hard to test this in Storybook

I have added some content to the story so the scrolling can be tested :)

**Comment by jaredhenderson** [comment]
Thanks, the story is easier to check now.

- [ ] Play button on portrait videos - can you add a 1px solid white border to the top and right side of this button? To make it visible against dark backgrounds, eg:

Screen Shot 2022-01-21 at 11 55 05 am

- [ ] SVG inside button doesn't seem to have the right ARIA properties?
- [ ] The autoplay behaviour seems a bit inconsistent when testing (gets stuck on repeat sometimes, even when not hovering)
  - When scrolling, video should only automatically play preview **once**, the **first time** it is scrolled into view, and then **NOT** play automatically again. So scroll/viewport based triggers should only ever fire one time per page load
  - Video preview can also play with user interaction on hover/focus, and should loop while still hovered/focused

**Comment by jaredhenderson** [comment]
- [ ] after video has been automatically triggered once by scroll/viewport, it should stop, **then reset time position to 0**. This used to be the case and has changed.
  - eg; video is 5 seconds long. play is triggered by scroll/viewport behaviour. video plays once from 0s to 5s, then pauses and resets time back to 0s. video should **not** be triggered by scroll/viewport behaviour more than once per page load.
  - Final state after playing example video preview should behave like below:
    - Should **not** stay paused at 5s
Screen Shot 2022-01-24 at 12 11 12 pm
    - Should be reset to 0s/opening frame
Screen Shot 2022-01-24 at 12 11 46 pm

- [ ] videos at the top of the viewport/page are not playing until the page is scrolled - they are visible straight away, so should be playing right away, not waiting for interaction 
- [ ] This component has a prop called `name` which is used in the examples to show the name of the person giving the testimonial. This area needs to be used for content as well, so `name` might not be appropriate for future content
- [ ] `name` is also being used to populate the alt text for the static image version. This might need to be a separate prop as `name` might be a paragraph value that doesn't relate to the image very well

Screen Shot 2022-01-24 at 12 27 06 pm


- [ ] Video previews don't seem to have ARIA titles/descriptions, eg; "Vanessa Brown on a campus lawn talking about her study at Melbourne University"

**Comment by anormand** [comment]
@gepifanio I think the problem is that you have a video component and button, but nothing in the DOM that indicates the relationship between them. 
If you add an aria-controls attribute to the button and link it to the id of the video, SortSite should be able to find the relationship.
Have a read of [Leonie Watsons article on this](https://tink.uk/using-the-aria-controls-attribute/). 
And the [MDN information](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls).

**Pull request merged**
