### PR TITLE
New sections from Today

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

We have a new wrapper component - `SectionAlt` - with a few new section examples. These new sections also use the new grid modifier `grid--lg` and `cell--lg` which are in the footer PR. 

One of the caveats with this is that I use the `<progressive-image>` component - which needs to be wrapped with a `<client-only>`  in Nuxt because when it evaluates the Vue template server side it doesn't match the DOM and throws up errors.

Also in the Storybook, it evaluates the `<progressive-image>` component so the *Source* in the story. I had a quick look through the code but can't see an easy way to ignore certain elements for template output.

When copying in the CMS, this should be 

```
<progressive-image class="section-alt__img" src="" alt="" aspect-ratio="0.4"></progressive-image>
```

## Components preview:
[Section - Standard with columns](https://deploy-preview-1611--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FSection&selectedStory=Standard%20%28with%20columns%29)
[Section - Standard with image](https://deploy-preview-1611--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FSection&selectedStory=Standard%20%28with%20image%29)
[Section - 3 Up](https://deploy-preview-1611--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FSection&selectedStory=3%20Up)
[Section - Columns](https://deploy-preview-1611--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Today%2FSection&selectedStory=Columns)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [x] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 339bdec8c1d63df354b77b088023583bb91f8700

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60987c4ae268790007911d3d

**Review by jaredh-um — CHANGES_REQUESTED** [review]
Hey Lucas,

Generally looking pretty good. One thing with the icons - to ensure sections where icons are used are able to use any SVGs from our library, they need to follow certain formatting which is detailed in the [docs](https://github.com/unimelb/pattern-lib/blob/dev/docs/icons.md). It's a little bit out of date, however.

I have updated the 3 SVGs you've supplied so they are consistent (enough) with our existing library - however, because colour is stripped from being hardcoded in the file, it needs to be set with CSS (using `color` or `fill`).

Similarly, the `width` and `height` values are stripped out, and this must also be set via CSS.

Are you able to update your code so they work with this more generic version of these files? (They'll appear black/currentColor by default otherwise)

**Comment by lmounsey** [comment]
Hi @jaredh-um - no worries, I've updated this to use SVG tags - I've also moved these icons to the Sprite sheet - I presume then in the CMS these will just be dropdown of icon names so then it can grab it from the pattern library

**Review by jaredh-um — APPROVED** [review]
👍 looks good

**Comment by lmounsey** [comment]
Hey @gepifanio 

I've fixed the documentation, includes the HTML template now as well as the source with the correct `<progressive-image>` markup to place in the CMS

**Review by gepifanio — APPROVED** [review]

**Comment by anormand** [comment]
1. Section - Standard with columns

Problem
- Bold is used to highlight words
- Most screen readers won't announce that text has been made bold 

Remedy 
- Use <storng> instead
https://support.siteimprove.com/hc/en-gb/articles/115002726312-Accessibility-Bold-vs-Strong-and-Italic-vs-Emphasis

2. Section - 3 Up

Problem
- SVGs are purely decorative but they are marked up as graphics

Remedy
- Hide the SVGs from assistive technologies by adding an attribute aria-hidden="true"

**Comment by lmounsey** [comment]
Committed a fix for the a11y issues above

**Comment by anormand** [comment]
Accessibility test passed.

Zero errors in:
- SortSite
- Siteimpreove
- HTML codeshiffer
- WAVE
- Lighthouse

**Pull request merged**
