### PR TITLE
Fix padding for sections in succession

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

Update the selector to fix padding on sections when two sections with just a white background are used in succession. The previous selector was applying to all sections, see https://find-a-course-preview-staging.netlify.app/find/micro-credentials/cybersecurity-technologies-for-defence/ (broken padding on mobile and reduced on desktop)

The selector is a bit ugly - initially I was trying to be a bit clever and not have to have say a default class of `section-alt--standard` but maybe that is easier. That would require a change though I presume to existing components in Matrix.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by jaredhenderson** [comment]
Hmm, I see what you mean @lmounsey. `section-alt` was added to the top level of each of these sections to get those rules to work, but as a result it's no longer specific enough just for the white background version.

Options would be:
- add specific class for white backgrounds as you mention (requires CMS template updates)
- use a rule to select only the applicable sections for this rule to apply (as you've included)

I'm not sure which is best, I guess it depends if we can settle the issue with the rule alone or whether it will complicate things later?

For the second option, it looks like the rule can be slightly simplified with the string selector * (as in, "doesn't contain this partial string anywhere in the class values":

```
.section-alt:not([class*='section-alt--']):not([class*='section-alt__']) + .section-alt:not([class*='section-alt--']):not([class*='section-alt__']) .section-alt__inner {
 padding-top:0
}
```

**Comment by lmounsey** [comment]
Thanks @jaredhenderson 

I think option 2 might be best in this scenario so that we can move the Microcert work out the door - with potentially a longer term look at option 1.

I like the simplification too - will update the selector. We can probably also remove the `:not([class*='section-alt__'])` part as well as it will only be the top level block class

**Comment by jaredhenderson** [comment]
No worries @lmounsey, sounds good

**Review by jaredhenderson — APPROVED** [review]
👍

**Review by gepifanio — APPROVED** [review]
looks good

**Pull request merged**
