### PR TITLE
feat(component): testimonials alt

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

New component for Testimonials. Includes three variations - text, long text and video.

[Testimonials Text](https://deploy-preview-1619--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FTestimonials&selectedStory=Text&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[Testimonials Long](https://deploy-preview-1619--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FTestimonials&selectedStory=Text%20%28Long%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[Testimonials Videos](https://deploy-preview-1619--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FTestimonials&selectedStory=Videos&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [x] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 0929d7ecd4e70166a2ff21b4cf9ca764d7eef7b6

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/609cc590e108ce00074b724d

**Review by gepifanio — CHANGES_REQUESTED** [review]
Could you please just update the docs exemplifying a real usage example that someone could just copy and paste and work straight out of the box:

Reference: https://github.com/unimelb/pattern-lib/pull/1615#discussion_r632193883

**Review by jaredhenderson — APPROVED** [review]
👍 looks good

**Review by gepifanio — APPROVED** [review]
Looks good

**Comment by anormand** [comment]
### Testimonials Text and Testimonials Long 

Both test OK.

### Testimonials Videos 

**Problem:**
- The label for the button is 'Play video Play 28s', which isn't very descriptive

**Remedy:**
- The Testimonials Videos are accompanied by headings, which should be linked to the buttons. 

**Example:**

Change:
```
<h3 class="testimonials-alt__title heading-sm">
    What is it like studying online compared to on campus?
  </h3>
<button aria-label="Play video Play 28s" class="video__btn">
```

To:
```
<h3 id="my-heading" class="testimonials-alt__title heading-sm">
    What is it like studying online compared to on campus?
  </h3>
<button aria-describedby="my-heading" aria-label="Play video Play 28s" class="video__btn">
```

**Comment by anormand** [comment]
aria-labelledby is now working.

**Problem**

SortSite is producing an error, because the label should contain the same text as the visual label.

**SortSite error message:**
The visual label must appear in the accessible name of links and controls.
Visual label: 
Play (28s) not in Play video 28s
People who use speech control rely on being able to select elements using the visual label displayed on screen. If this isn't part of the accessible name, they can't select elements by name.
Line 1022 WCAG 2.0 A F96

**Remedy:**
Change:
`<button aria-label="Play video  28s" aria-describedby="testimonial-3703" class="video__btn" style="">`
To:
`<button aria-label="Play (28s) video" aria-describedby="testimonial-3703" class="video__btn" style="">`

**Comment by anormand** [comment]
Video component now reads out correctly. Tested with Voiceover + Chrome

**Pull request merged**
