### PR TITLE
Chore: css body and main updates

### PR DESCRIPTION
**Pull request by gepifanio**
# Description

Fixes https://github.com/unimelb/pattern-lib/issues/1710

- Changed background-color on the body to match colour on the bottom of the footer.
- Added a min-height to the main content block so pages have a minimum height of 25rem
- That fixes the footer overflow, however as the page header colour is another navy you can see the page header overflow colour darker with this change:

image

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by jaredhenderson** [comment]
- Can you provide more information please? URL example? Where are you seeing this issue? That 'overflow' should not be occurring in a header in the first place.

**Comment by gepifanio** [comment]
> * Can you provide more information please? URL example? Where are you seeing this issue? That 'overflow' should not be occurring in a header in the first place.

That overflow happens only if you scroll backward when the header jumps down, is unlikely a user would be scrolling past the header, also when the user stops scrolling it would scroll back for the page header to stick at the top.

**Comment by jaredhenderson** [comment]
> URL example? Where are you seeing this issue? 

What URL/environment/browser are you talking about? I can't do much with just a picture. Have you compared this to previous behaviour?

**Comment by gepifanio** [comment]
> > URL example? Where are you seeing this issue?
> 
> What URL/environment/browser are you talking about? I can't do much with just a picture. Have you compared this to previous behaviour?

We don't have a preview link for that, The photo example is what I have tested in a live page changing the CSS properties, and Storybook cant replicate that. 

But basically, before the header colour and the page body colour were the same, you wouldn't see the colour difference whereas now they are different.

**Review by jaredhenderson — APPROVED** [review]
They weren't quite the same before - the header is Brand `navy-dark` and the page bg was `background-secondary-navy` which is only a little bit darker, so it was less obvious.

What browser is this happening in? I can't replicate it in Safari, Firefox or Chrome on desktop.

Anyway if that's all it is, we can't do much about it - we can't set the body colour to two different things. Probably looks worse with white so this is fine by me

**Pull request merged**
