### PR TITLE
Add course index

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

Adding the mini course index to our list of sections.

[Component preview](https://deploy-preview-1624--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FSection&selectedStory=Course%20Index&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 887237136630bde8a2a5b38b6e102c0ddf0773f9

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60a45659d920870007b694a4

**Review by gepifanio — APPROVED** [review]
Looks good

**Review by jaredhenderson — CHANGES_REQUESTED** [review]
Just a couple of things..
- [x] Please remove `letter-spacing` property from the course cards class `.card-course__type` and leave as default (eg; `0`) - probably a legacy holdover
- [ ] Need documentation on how to use for Storybook? Maybe still underway

**Comment by lmounsey** [comment]
Hi @jaredhenderson 

Got a commit deploying now for the `letter-spacing`

RE: documentation - we are reusing existing components here so I haven't included any additional documentation, similar to how I've documented the other sections - I think the README has all the info necessary

**Review by jaredhenderson — APPROVED** [review]
👍 Looks good. Re: documentation I meant more how the courses actually get populated in the list, but is that a FAC thing?

**Comment by lmounsey** [comment]
I believe this will automated in Matrix from what Tom has indicated - so the CMS editor would probably choose what type of course (undergraduate, graduate, etc) - it's detailed in JIRA so I think it's covered

**Pull request merged**
