### PR TITLE
feature(styled-select) update to new design

### PR DESCRIPTION
**Pull request by TimMansell**
https://github.com/unimelb/find-a-course/issues/1491

This PR only covers the dropdown part (minus the 3 courses available)

Screen Shot 2019-11-25 at 3 41 38 pm

Updated tabs to allow for a select dropdown tab changer.

Components affected:

- styled select https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Forms&selectedStory=Styled%20select&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
- filters https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Filter%20%2F%20Components&selectedStory=Accordion%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
- tabs https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Tabs&selectedStory=Tabs%2C%20using%20a%20select&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 8e3f20dde345205713c3d018d4e04050299647f1

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5ddb34da3878710008152a65

**Comment by jonathan-doc** [comment]
The selector's content should not have a white background; it should either be transparent or inherit its parent container's background colour.

Looks good otherwise 👍

**Comment by TimMansell** [comment]
> The selector's content should not have a white background; it should either be transparent or inherit its parent container's background colour.
> 
> Looks good otherwise 👍

Fixed.

**Comment by TimMansell** [comment]
> Just @jonathan-doc comments, otherwise, pretty good 👌

Fixed.

**Comment by TimMansell** [comment]
@dkevey are you using `tabs` and `styled-select` in the CMS? Just checking to see if we need to bother with upgrade notes.

@gepifanio can you follow up with @dkevey

**Comment by dkevey** [comment]
yes we are using those @TimMansell @gepifanio thanks

**Comment by TimMansell** [comment]
@dkevey, can you send me the url of a page that uses them? I can't find the in `Matrix Controlled Environment Gen 2`

**Pull request merged**
