### PR TITLE
Add new component for section image and document use of quick links

### PR DESCRIPTION
**Pull request by lmounsey**
# Description

New Section component used with Quick links

[Component preview](https://deploy-preview-1623--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FSection&selectedStory=Quick%20Links&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] Make sure to do not repeat yourself (DRY)
- [x] Snapshots tested
- [x] A11y tested
- [x] CSS utilises BEM naming convention and structure
- [x] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [x] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [x] My changes generate no new warnings
- [x] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [x] A11y tested
- [ ] Crossbrowser tested in at least IE11

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 6a9012f71146f2c299106e548ec7bf4f1d6ab156

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60a38f1595cf3300079ab157

**Review by gepifanio — APPROVED** [review]
looks good

**Review by jaredhenderson — APPROVED** [review]
👍 looks good

**Comment by anormand** [comment]
Passes accessibility check

**Pull request merged**
