### PR TITLE
fix(component): split section header

### PR DESCRIPTION
**Pull request by gepifanio**
Ticket: https://github.com/unimelb/pattern-lib/issues/1317

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit 3fa91b54bc5d0acb6ee386153f9844b20a4d2170

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5dad30e1bb634c00072ea38b

**Comment by TimMansell** [comment]
Comment from @jonathan-doc 

https://github.com/unimelb/pattern-lib/issues/1317#issuecomment-544343827

**Comment by TimMansell** [comment]
@jonathan-doc can you do one last test to make sure everything you picked up has been fixed.

**Comment by jonathan-doc** [comment]
Looks good to me @TimMansell  @gepifanio

**Pull request merged**
