### PR TITLE
update(component): carousel image position and story

### PR DESCRIPTION
**Pull request by gepifanio**
Tickets: #1217 [#542](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/542)

### CODE REVIEW

**Comment by gepifanio** [comment]
Comment: Deploy Started

Building with commit a83fe3e7f5cf0704aa3e1610b6c6d37decd23263

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/5d41150a9707af000858f9d1

**Comment by jaredh-um** [comment]
Two things...
- [ ] can you change the image URLs in this story to be something like `https://source.unsplash.com/random/2000x1000` because the Matrix images won't load unless you're logged in (403 error)

- [ ] when there's the maximum amount of description text and a minimum amount of text the bottom container changes height when the story changes. are we able to set this so the minimum height is the height of the biggest story?

**Comment by jaredh-um** [comment]
Hey @gepifanio, can you try the following for the height issue:
- [ ] set `margin-bottom: .5rem` on `.carousel__aside`

Also
- [ ] set `a:active` on `.carousel__navigation-link` to white (it's currently a dirty blue and makes the text invisible during the click)

**Comment by gepifanio** [comment]
> On second thought, I think we should set a default position (to center) if no `imagePosition` prop is not passed.

Not sure how to do that, apparently the images at the moment that hasn't been set up the position is `top left` aligned.

**Comment by TimMansell** [comment]
Hi @jaredh-um, are you ok with this being merged?

**Pull request merged**
